nodeLinker: node-modules

npmScopes:
  agendando_ai:
    npmRegistryServer: "https://verdaccio.barbeia.ai"
    npmAlwaysAuth: true
    npmAuthToken: "ZDkzN2JjYWU4MWY5NzA5OTQ4MTNiMmI0ZDhiMTQ4M2U6ZGFhYzQ3NjhjOWFmZGI5Mzc4ZmQ3ZGFjZDFjZA=="